const QUERY_KEY = {
  GET_CHANNELS: "GET_CHANNELS",
  GET_MESSAGE_HISTORY: "GET_MESSAGE_HISTORY",
  GET_NEW_MESSAGES: "GET_NEW_MESSAGES",
  GET_FRIENDS_LIST: "GET_FRIENDS_LIST",
  GET_PENDING_REQUESTS: "GET_PENDING_REQUESTS",
  GET_P2P_MESSAGE_HISTORY: "GET_P2P_MESSAGE_HISTORY",
  GET_P2P_NEW_MESSAGES: "GET_P2P_NEW_MESSAGES",
  GET_SERVER_INFO: "GET_SERVER_INFO",
};

export default QUERY_KEY;
